### ISSUE TITLE
liquibase.exception.SetupException when running resulting changelog

### ISSUE THREAD

**Issue by garyhodgson** [ljnelson/liquibase-maven-plugin#1]
Hi,

I'm having a problem using the assembleChangeLog goal.  The plugin appears to work correctly and the aggregate changelog is generated, however liquibase can't seem to process changelogs from within jar files (or at least that's how I interpret it).

The resulting changelog file entry looks correct, e.g. 

```
<include file="jar:file:/D:/Tools/Maven/.m2/repository/com/garyhodgson/test/liquibase-test-a/1.0-SNAPSHOT/liquibase-test-a-1.0-SNAPSHOT.jar!/META-INF/liquibase/changelog.xml"/>
```

But attempting to use this changelog results in :

> Failed to execute goal org.liquibase:liquibase-maven-plugin:3.3.2:status (default) on project liquibase-test-b: Error setting up or running Liquibase: liquibase.exception.SetupException: jar:file:/D:/Tools/Maven/.m2/repository/com/garyhodgson/test/liquibase-test-a/1.0-SNAPSHOT/liquibase-test-a-1.0-SNAPSHOT.jar!/META-INF/liquibase/changelog.xml does not exist

Is there anything I'm perhaps doing wrong somewhere along the line?  Any insight would be appreciated.

**Comment by garyhodgson** [comment]
Hi again,

So I did some further digging around and came across your "liquibase-extensions" project which I see should add the necessary ResourceAccessor.  However, adding it to the plugin dependency appears not to work.

In another attempt I tried using your "artifact-maven-plugin", which also worked, but also produced a jar:file URL, and so suffers the same problem as above.

Any indication of how to get the liquibase-extensions to work would be appreciated.

**Comment by ljnelson** [comment]
Hi there; I'll try to write up something here.  I apologize for the delay!  The combination of projects certainly does work together.

**Comment by garyhodgson** [comment]
No problem. In the meantime I simply merged the URLresourceAccessor
directly into a fork of liquibase itself. It appears to be working great.

**Comment by ljnelson** [comment]
Just so we're clear: the `liquibase-maven-plugin` generates a `changelog.xml` file (as you have discovered :-)).  It doesn't invoke Liquibase in any way (this I grant you is counterintuitive from the name of the plugin).

So how this file gets processed by Liquibase is indeed out of band.  Indeed the URLs generated by this plugin are not handled by Liquibase itself.  If you want to handle them, and you are running Liquibase from the command line, then my `liquibase-extensions` project contains a `URLResourceAccessor` (as you've found) that will handle these URLs, and so you'd put this jar file in the Liquibase tool's `lib` directory.  I believe that will add the `URLResourceAccessor` to the classpath and you can then specify it with a command line option whose name I've forgotten, if indeed such an option exists.

Personally I don't process these files from the command line.  I process them from unit/integration tests, where I am in charge of creating my own `Liquibase` object in my unit test.  Because I'm in charge there, I add my extension project to the test-scoped dependencies _of my project_, not of this plugin.

Does this make sense?  I'll also write up a little more on how several of my Liquibase-related projects can be chained together to help with unit/integration testing.

**Comment by garyhodgson** [comment]
Hi - yup, that's clear :)   I am running liquibase via the maven plugin, and when I tried adding liquibase-extensions as a dependency it didn't appear to be picked up.  However I will test again as I tried several things and can't remember if I added it as a dependency to the project, or just to the liquibase plugin itself.

As an aside, in case you are already considering renaming the project, at the moment there is a naming conflict if you want to run the maven liquibase command directly, i.e. If I have both your plugin and the liquibase version specifiec in the pom, and then run `mvn liquibase:status` I get the following error:

```
[ERROR] Could not find goal 'status' in plugin com.edugility:liquibase-maven-plugin:1.0.1-SNAPSHOT among available goals assembleChangeLog -> [Help 1]
```

The workaround is to specify the fully-qualified name of the plugin, e.g. `mvn org.liquibase:liquibase-maven-plugin:status`

For what it's worth I think `liquibase-assembly-plugin` has a nice ring to it :)

**Comment by ljnelson** [comment]
OK.  I'm going to close this issue, as the format of the XML file is legal, and, assuming you have the right `ResourceAccessor` in play, things will work (i.e. there's nothing really wrong here).  Does that seem correct to you?

I'll add another issue to update the `README` or [site documentation](http://ljnelson.github.io/liquibase-maven-plugin/) with more information about exactly what this plugin does and does not do.

**Comment by garyhodgson** [comment]
Hi again, 

(I wrote the following at the same time as you answered above - I'm fine with you closing this issue as it appears to be a problem with the liquibase-extensions plugin I think)

Just to let you know that I tried adding the `liquibase-extensions` artifact as a dependency to both the project and to the liquibase plugin and the URLResourceAccessor does not appear to be being used. In both cases liquibase complains with 

```
liquibase.exception.SetupException: file:/T:/workspace/../target/classes/META-INF/liquibase/changelog.xml does not exist
```

I tried both 1.0.3 and 1.0.4-SNAPSHOT

Looking at the liquibase code I don't see a point where resource accessors are dynamically picked up, but perhaps I am simply not seeing it.  When I modified the my liquibase fork I added the URL accessor to the composite within the maven plugin.

Thanks for your help on this.

**Comment by ljnelson** [comment]
No problem.  I'll close the issue.  I don't believe that the Liquibase plugin allows you to specify `ResourceAccessor` implementations (which IMHO is a shortcoming).

(Also, to be careful, the [`liquibase-extensions` project](http://ljnelson.github.io/liquibase-extensions/) is not a plugin.)
